import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NewsProvider } from "../../context/NewsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "perpenka",
  description: "Generated by create next app",
  // icons: {
  //   icon: ['/favicon.ico?v=1'],
  //   apple: ['/apple-touch-icon.png?v=4'],
  //   shortcut:['/apple-touch-icon.png']
  // },
  // manifest: '/site.webmanifest'
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <NewsProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
      </NewsProvider>
  );
}
